export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST';
export const FETCH_CITY= 'FETCH_CITY';
export const FETCH_COUNTRY = 'FETCH_COUNTRY';
export const FETCH_TEMP = 'FETCH_TEMP';
export const FETCH_HUMIDITY = 'FETCH_HUMIDITY';
export const FETCH_CONDITIONS = 'FETCH_CONDITIONS';
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';